version: '3'
networks:
  "!docker-ssh-exec":
    external: true
volumes:
  data:
services:
  app:
    build: .
    image: docker.voxops.net/ruby:2.5-3.0.3
    environment:
      - IMAGE_VERSION=2.5.2
    volumes:
      - ./ruby/entrypoint_scripts/base_image_check.sh:/opt/entrypoint/base_image_check.sh
      - ./ruby/entrypoint_scripts/aws-policies:/opt/policies
      - ${AWS_SIGNED_URL_KEY}:/opt/policies/aws-signed-url-private-key.pem
    networks:
      - default
      - "!docker-ssh-exec"
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    volumes:
      - .:/usr/share/nginx/html
