source "https://rubygems.org"

group :development do
  gem "capistrano",              '~> 2.15.5'
  gem 'capistrano-slack-notify', '~> 1.3.0'
  gem 'capistrano-docker', :git => 'git@github.com:voxmedia/capistrano-docker.git', :tag => "1.196"
end
